james_develin = PlayerCard.create do |card|
  card.first_name                     = 'James'
  card.last_name                      = 'Develin'
  card.overall                        = 94
  card.team_chemistry_id              = Chemistry.by_team_city(:new_england).first.id
  card.program                        = TEAM_OF_THE_YEAR
  card.position                       = Position::FULLBACK
  card.salary_cap_value               = 47
  card.height_in_inches               = 75
  card.weight_in_pounds               = 255
  card.speed                          = 71
  card.strength                       = 87
  card.agility                        = 70
  card.acceleration                   = 80
  card.awareness                      = 94
  card.catching                       = 85
  card.jumping                        = 64
  card.stamina                        = 81
  card.injury                         = 90
  card.trucking                       = 90
  card.elusiveness                    = 72
  card.ball_carrier_vision            = 76
  card.stiff_arm                      = 88
  card.spin_move                      = 75
  card.juke_move                      = 78
  card.carrying                       = 91
  card.route_running                  = 79
  card.catch_in_traffic               = 79
  card.spectacular_catch              = 73
  card.release                        = 74
  card.throw_power                    = 64
  card.throw_accuracy_short           = 54
  card.throw_accuracy_mid             = 55
  card.throw_accuracy_deep            = 54
  card.throw_on_the_run               = 56
  card.play_action                    = 55
  card.run_block                      = 91
  card.pass_block                     = 86
  card.impact_blocking                = 95
  card.tackle                         = 81
  card.hit_power                      = 82
  card.power_moves                    = 57
  card.finesse_moves                  = 57
  card.block_shedding                 = 57
  card.pursuit                        = 81
  card.play_recognition               = 59
  card.man_coverage                   = 55
  card.zone_coverage                  = 57
  card.press                          = 55
  card.kick_power                     = 62
  card.kick_accuracy                  = 62
  card.kick_return                    = 66
  card.trait_clutch                   = false
  card.trait_covers_ball              = 'Brace for All Hits'
  card.trait_fights_for_extra_yards   = true
  card.trait_drops_open_passes        = false
  card.trait_makes_sideline_catches   = false
  card.trait_high_motor               = true
  card.trait_makes_aggressive_catches = false
  card.trait_makes_rac_catches        = false
  card.trait_makes_possession_catches = false
  card.trait_drops_open_passes        = false
  card.trait_makes_sideline_catches   = false
  card.trait_penalty                  = 'Normal'
end
PlayerCardChemistry.create(player_card: james_develin, chemistry: MOVE_THE_STICKS, tier: 2)
PlayerCardChemistry.create(player_card: james_develin, chemistry: IDENTIFIED, tier: 1)

[POUND_THE_ROCK, MOVE_THE_STICKS, GO_DEEP, TOUGHNESS].each do |chemistry|
  christian_okoye = PlayerCard.create do |card|
    card.first_name                     = 'Christian'
    card.last_name                      = 'Okoye'
    card.overall                        = 98
    card.team_chemistry_id              = Chemistry.by_team_city(:kansas_city).first.id
    card.program                        = ULTIMATE_LEGENDS
    card.position                       = Position::FULLBACK
    card.salary_cap_value               = 71
    card.height_in_inches               = 73
    card.weight_in_pounds               = 253
    card.speed                          = 90
    card.strength                       = 94
    card.agility                        = 85
    card.acceleration                   = 95
    card.awareness                      = 97
    card.catching                       = 72
    card.jumping                        = 83
    card.stamina                        = 90
    card.injury                         = 96
    card.trucking                       = 97
    card.elusiveness                    = 77
    card.ball_carrier_vision            = 97
    card.stiff_arm                      = 97
    card.spin_move                      = 79
    card.juke_move                      = 83
    card.carrying                       = 98
    card.route_running                  = 68
    card.catch_in_traffic               = 67
    card.spectacular_catch              = 62
    card.release                        = 66
    card.throw_power                    = 35
    card.throw_accuracy_short           = 25
    card.throw_accuracy_mid             = 25
    card.throw_accuracy_deep            = 20
    card.throw_on_the_run               = 20
    card.play_action                    = 20
    card.run_block                      = 91
    card.pass_block                     = 85
    card.impact_blocking                = 93
    card.tackle                         = 70
    card.hit_power                      = 55
    card.power_moves                    = 25
    card.finesse_moves                  = 25
    card.block_shedding                 = 40
    card.pursuit                        = 40
    card.play_recognition               = 25
    card.man_coverage                   = 20
    card.zone_coverage                  = 20
    card.press                          = 20
    card.kick_power                     = 20
    card.kick_accuracy                  = 20
    card.kick_return                    = 28
    card.trait_clutch                   = false
    card.trait_covers_ball              = 'Brace vs. Medium Hitters'
    card.trait_fights_for_extra_yards   = true
    card.trait_drops_open_passes        = false
    card.trait_makes_sideline_catches   = false
    card.trait_high_motor               = true
    card.trait_makes_aggressive_catches = false
    card.trait_makes_rac_catches        = false
    card.trait_makes_possession_catches = false
    card.trait_drops_open_passes        = false
    card.trait_makes_sideline_catches   = false
    card.trait_penalty                  = 'Normal'
  end
  PlayerCardChemistry.create(player_card: christian_okoye, chemistry: chemistry, tier: 2)
  PlayerCardChemistry.create(player_card: christian_okoye, chemistry: BATTLE_READY, tier: 1)
end
