bo_jackson = PlayerCard.create do |card|
  card.first_name                     = 'Bo'
  card.last_name                      = 'Jackson'
  card.overall                        = 95
  card.team_chemistry_id              = Chemistry.by_team_city(:oakland).first.id
  card.program                        = SNOW_BEAST
  card.position                       = Position::HALFBACK
  card.salary_cap_value               = 80
  card.height_in_inches               = 73
  card.weight_in_pounds               = 227
  card.speed                          = 94
  card.carrying                       = 93
  card.acceleration                   = 95
  card.elusiveness                    = 90
  card.stamina                        = 96
  card.juke_move                      = 96
  card.spin_move                      = 93
  card.stiff_arm                      = 96
  card.trucking                       = 96
  card.ball_carrier_vision            = 94
  card.agility                        = 94
  card.weight_in_pounds               = 227
  card.catching                       = 74
  card.catch_in_traffic               = 70
  card.route_running                  = 68
  card.spectacular_catch              = 63
  card.awareness                      = 93
  card.jumping                        = 94
  card.trait_clutch                   = true
  card.trait_covers_ball              = 'Brace vs. Medium Hitters'
  card.trait_fights_for_extra_yards   = true
  card.trait_makes_aggressive_catches = false
  card.trait_makes_rac_catches        = false
  card.trait_makes_possession_catches = false
  card.trait_drops_open_passes        = false
  card.trait_makes_sideline_catches   = false
  card.trait_high_motor               = true
  card.trait_penalty                  = 'Normal'
end
PlayerCardChemistry.create(player_card: bo_jackson, chemistry: POUND_THE_ROCK, tier: 2)
PlayerCardChemistry.create(player_card: bo_jackson, chemistry: BATTLE_READY, tier: 1)

ladainian_tomlinson = PlayerCard.create do |card|
  card.first_name                         = 'LaDainian'
  card.last_name                          = 'Tomlinson'
  card.overall                            = 98
  card.team_chemistry_id                  = Chemistry.by_team_city(:los_angeles).first.id
  card.program                            = LEVEL_MASTER
  card.position                           = Position::HALFBACK
  card.salary_cap_value                   = 81
  card.height_in_inches                   = 70
  card.weight_in_pounds                   = 215
  card.speed                              = 95
  card.carrying                           = 96
  card.acceleration                       = 97
  card.elusiveness                        = 96
  card.stamina                            = 98
  card.juke_move                          = 94
  card.spin_move                          = 95
  card.stiff_arm                          = 98
  card.trucking                           = 81
  card.ball_carrier_vision                = 96
  card.agility                            = 97
  card.weight_in_pounds                   = 215
  card.catching                           = 88
  card.catch_in_traffic                   = 82
  card.route_running                      = 89
  card.spectacular_catch                  = 73
  card.awareness                          = 96
  card.jumping                            = 94
  card.trait_clutch                       = true
  card.trait_covers_ball                  = 'Brace for All Hits'
  card.trait_fights_for_extra_yards       = true
  card.trait_makes_aggressive_catches     = false
  card.trait_makes_rac_catches            = false
  card.trait_makes_possession_catches     = false
  card.trait_drops_open_passes            = false
  card.trait_makes_sideline_catches       = false
  card.trait_high_motor                   = true
  card.trait_penalty                      = 'Normal'
end
PlayerCardChemistry.create(player_card: ladainian_tomlinson, chemistry: MOVE_THE_STICKS, tier: 2)
PlayerCardChemistry.create(player_card: ladainian_tomlinson, chemistry: NEVER_STUMBLE, tier: 1)
